declare module 'vant' {
  export const Popup: any
  export const NavBar: any
  export const Icon: any
  export const Grid: any
  export const GridItem: any
  export const Cell: any
  export const CellGroup: any
  export const Button: any
  export const Tag: any
  export const Circle: any
  export const Loading: any
  export const Empty: any
  export const NoticeBar: any
  export const Checkbox: any
  export const Field: any
  export const Form: any
  export const ActionSheet: any
  export const Toast: any
  export const Switch: any
  export const Steps: any
  export const Step: any
  export const showDialog: any
  export const showConfirmDialog: any
  export const showToast: any
  export const showLoadingToast: any
  export const closeToast: any
  export const Popover: any
  export const Image: any
  export const ImagePreview: any
  export const List: any
  export const ListItem: any
  export const Divider: any
  export const Space: any
  export const Tab: any
  export const Tabs: any
  export const Tabbar: any
  export const TabbarItem: any
  export const NavBar: any
  export const Search: any
  export const SwipeCell: any
  export const Collapse: any
  export const CollapseItem: any
  export const Picker: any
  export const DatetimePicker: any
  export const Overlay: any
  export const Scrollspy: any
  export const PullRefresh: any
}

